version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Use this if you want to connect to a cloud DB, otherwise it will use local Postgres container
      LOCAL_DB_URL: "${LOCAL_DB_URL:-postgres://postgres:postgres@db:5432/localdb?sslmode=disable}"
      # URL of your external API
      EXTERNAL_API_URL: "${EXTERNAL_API_URL:-http://host.docker.internal:3000/api/summary}"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: localdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Only start this container if LOCAL_DB_URL is not pointing to cloud
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  pgdata:
